name: krutidevtounicode
description: This package is created to convert the Krutidev font to Unicode 
version: 1.0.2
homepage: https://github.com/ravitaak/krutidevtounicode

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
